spring.application.name=live_project_media
server.port=${SERVER_PORT}

# ===== 데이터베이스 설정 =====

# MySQL 연결 설정
spring.datasource.url=${SPRING_DATABASE_URL}
spring.datasource.username=${SPRING_DATABASE_USERNAME}
spring.datasource.password=${SPRING_DATABASE_PASSWORD}
spring.datasource.driver-class-name=${SPRING_DATABASE_DRIVER}

# JPA 설정
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.MySQLDialect}
spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:mysql}
spring.jpa.open-in-view=${SPRING_JPA_OPEN_IN_VIEW:true}

# 데이터베이스 초기화 설정
spring.sql.init.mode=${SPRING_SQL_INIT_MODE:always}
spring.sql.init.schema-location=${SPRING_SQL_INIT_SCHEMA_LOCATION:classpath:""}
spring.sql.init.data-location=${SPRING_SQL_INIT_DATA_LOCATION:""}

# CloudFlare 설정
app.r2.video-bucket-name=${APP_R2_VIDEO_BUCKET_NAME}
app.r2.endpoint=${SPRING_CLOUD_R2_ENDPOINT}
app.r2.access-key=${SPRING_CLOUD_R2_ACCESS_KEY}
app.r2.secret-key=${SPRING_CLOUD_R2_SECRET_KEY}
app.r2.original-video-bucket-name=${APP_R2_ORIGINAL_VIDEO_BUCKET_NAME}
app.r2.transcoding-video-bucket-name=${APP_R2_TRANSCODING_VIDEO_BUCKET_NAME}

# ===== Kafka 설정 =====
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVER}
spring.kafka.consumer.group-id=${SPRING_KAFKA_CONSUMER_GROUP_ID}
spring.kafka.consumer.auto-offset-reset=${SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET}
spring.kafka.consumer.key-deserializer=${SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER}
spring.kafka.consumer.value-deserializer=${SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER}
#spring.kafka.consumer.properties.spring.json.use.type.headers:${SPRING_KAFKA_CONSUMER_USE_TYPE}
#spring.kafka.consumer.properties.spring.json.trusted.packages:${SPRING_KAFKA_CONSUMER_TRUSTED_PACKAGES}
spring.kafka.producer.key-serializer=${SPRING_KAFKA_PRODUCER_KEY_SERIALIZER}
spring.kafka.producer.value-serializer=${SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER}

app.kafka.topic.video-complete.name=${APP_KAFKA_TOPIC_VIDEO_COMPLETE_NAME}
app.kafka.topic.video-complete.partitions=${APP_KAFKA_TOPIC_VIDEO_COMPLETE_PARTITIONS}
app.kafka.topic.video-complete.replicas=${APP_KAFKA_TOPIC_VIDEO_COMPLETE_REPLICAS}
app.kafka.topic.video-complete.retention-ms=${APP_KAFKA_TOPIC_VIDEO_COMPLETE_RETENTION_MS}
app.kafka.topic.video-complete.cleanup-policy=${APP_KAFKA_TOPIC_VIDEO_COMPLETE_CLEANUP_POLICY}

app.kafka.consumer.partitions=${APP_KAFKA_CONSUMER_PARTITIONS}